import type { FsStatReport as FsStatReportDTO } from "#types";

/**
 * FsStatReport represent the report generated by the FSStat library.
 */
export interface FsStatReport {
  /**
   * The total number of files contained in the given path and all its subdirectories.
   */
  readonly numOfFiles: number;

  /**
   * An array where the i-th element represents the number of files whose size falls into the i-th band.
   * The bands are defined by dividing the range of file sizes (from 0 to maxSize) into equal intervals.
   */
  readonly sizeBands: number[];

  /**
   * Updates the report with a new file size, incrementing the total number of files and updating the appropriate size band.
   * @param fileSize The size of the file to be added to the report.
   * @returns The updated FsStatReport instance.
   */
  updateReport(fileSize: number): FsStatReport;

  /**
   * Converts the report into the exported FsStatReport format.
   * @return An object containing the total number of files and the size bands for external use.
   */
  dto(): FsStatReportDTO;
}

class FsStatReportImpl implements FsStatReport {
  private _numOfFiles: number;
  private _sizeBands: number[];

  constructor(
    readonly maxSize: number,
    readonly bands: number,
  ) {
    this._numOfFiles = 0;
    this._sizeBands = new Array(bands + 1).fill(0);
  }

  updateReport(fileSize: number): FsStatReport {
    this.numOfFiles++;
    const bandIndex = this.getBandIndex(fileSize);
    const currentCount = this.sizeBands[bandIndex] ?? 0;
    this.sizeBands[bandIndex] = currentCount + 1;
    return this;
  }

  private set numOfFiles(value: number) {
    this._numOfFiles = value;
  }

  get numOfFiles(): number {
    return this._numOfFiles;
  }

  private set sizeBands(value: number[]) {
    this._sizeBands = value;
  }

  get sizeBands(): number[] {
    return this._sizeBands;
  }

  private getBandIndex(size: number): number {
    const bandSize = this.maxSize / this.bands;
    const fileBand = Math.floor(size / bandSize);
    return fileBand >= this.bands ? this.bands : fileBand;
  }

  dto(): FsStatReportDTO {
    return {
      numOfFiles: this.numOfFiles,
      sizeBands: this.sizeBands,
    };
  }
}

export function FsStatReport(maxSize: number, bands: number): FsStatReport {
  return new FsStatReportImpl(maxSize, bands);
}
